//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUThanhLy_VIEW
    {
        public int maptl { get; set; }
        public Nullable<int> Madv { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<decimal> Tổng_tiền_thanh_lý { get; set; }
    }
}
