//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTra_VIEW
    {
        public int mapt { get; set; }
        public Nullable<int> MaPM { get; set; }
        public Nullable<int> MaThe { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<decimal> Tổng_tiền_xử_lý { get; set; }
    }
}
