//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVienBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP_VIEW
    {
        public int MAPN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> TỔNG_TIỀN { get; set; }
        public Nullable<int> TỔNG_SÁCH { get; set; }
    }
}
